---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmqservice
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: rabbitmqservice
  replicas: 1
  template:
    metadata:
      labels:
        app: rabbitmqservice
    spec:
      containers:
      - name: rabbitmqservice
        image: rabbitmq:3.11-management
        env:
        - name: RABBITMQ_DEFAULT_USER
          value: root
        - name: RABBITMQ_DEFAULT_PASS
          value: password
        ports:
        - containerPort: 5672
        - containerPort: 15672
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmqservice
  labels:
    app: rabbitmqservice
spec:
  ports:
  - port: 5672
    targetPort: 5672
    protocol: TCP
    name: rabbitmqservice-port-5672
  - port: 15672
    targetPort: 15672
    protocol: TCP
    name: rabbitmqservice-port-15672
  selector:
    app: rabbitmqservice
  type: ClusterIP