version: '3'
services:
  zookeeper:
    image: debezium/zookeeper:1.2
    hostname: zookeeper
    ports:
     - 2181:2181
     - 2888:2888
     - 3888:3888  
  kafka:
    image: debezium/kafka:1.2
    hostname: kafka
    ports:
     - 9092:9092
    links:
     - zookeeper
    environment:
     - ZOOKEEPER_CONNECT=zookeeper:2181
  mysqldb:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - "3306:3306"

