apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP
      name: mongodb-port-27017
    - port: 27018
      targetPort: 27018
      protocol: TCP
      name: mongodb-port-27018
    - port: 27019
      targetPort: 27019
      protocol: TCP
      name: mongodb-port-27019
  selector:
    app: mongodb
  type: ClusterIP