# TOPO
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: toposervice
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: toposervice
  template:
    metadata:
      labels:
        app: toposervice
    spec:
      securityContext:
        runAsUser: 1001
        runAsGroup: 3000
        fsGroup: 2000    
      restartPolicy: Always
      containers:
      - name: toposervice
        image: {{ .Values.toposervice.image.name }}:{{ .Values.toposervice.image.version }}        
        env:
        - name: TOPO_PORT
          value: "8181"
        - name: SPRING_DATA_MONGODB_HOST
          value: mongodb
        - name: SPRING_DATA_MONGODB_PORT
          value: "27017"
        - name: SPRING_DATA_MONGODB_DATABASE
          value: topoDB
        - name: SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE
          value: admin
        - name: SPRING_DATA_MONGODB_USERNAME
          value: root
        - name: SPRING_DATA_MONGODB_PASSWORD
          value: password
        ports:
        - containerPort: 8181
  replicas: 1

---
apiVersion: v1
kind: Service
metadata:
  name: toposervice
  labels:
    app: toposervice
spec:
  selector:
    app: toposervice
  ports:
  - port: 8181
    targetPort: 8181
    protocol: TCP
    name: toposervice-port
  type: ClusterIP