services:
  server:
    image: mastercloudapps/server:v1.23
    ports:
      - 8080:8080
    env_file:
        - properties.env
    depends_on:
      mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    restart: on-failure

  weatherservice:
    image: mastercloudapps/weatherservice:v1.23
    ports:
      - 9090:9090
    env_file:
        - properties.env
    restart: on-failure

  planner:
    image: mastercloudapps/planner:v1.23
    env_file:
        - properties.env
    depends_on:
      - weatherservice
      - toposervice
      - rabbitmq
    command: bash -c "
      ./wait-for-it.sh weatherservice:9090 --
      ./wait-for-it.sh toposervice:8181 --
      ./wait-for-it.sh rabbitmq:5672 --
      java -jar planner.jar"
    restart: on-failure

  toposervice:
    image: mastercloudapps/toposervice:v1.23
    ports:
      - 8181:8181
    env_file:
        - properties.env
    depends_on:
      - mongodb
    restart: on-failure

  mysql:
    image: mysql:8.0
    ports:
      - 3306:3306
    env_file:
        - properties.env
    volumes:
      - ./mysql_db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-uroot", "-p$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 5s
      start_period: 10s
      retries: 5
    restart: always

  mongodb:
    image: mongo:5.0-focal
    ports:
      - 27017-27019:27017-27019
    env_file:
        - properties.env
    volumes:
      - ./mongo_db:/data/db
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      start_period: 10s
      retries: 5
    restart: always

  rabbitmq:
    image: rabbitmq:3.11-management
    ports:
      - 5672:5672
      - 15672:15672
    env_file:
        - properties.env
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "check_port_connectivity" ]
      interval: 5s
      timeout: 5s
      start_period: 10s
      retries: 5
    restart: always