# PLANNER
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: planner
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: planner
      networking/allow-rabbitmq-access: "true"
      networking/allow-toposervice-access: "true"
      networking/allow-weatherservice-access: "true"      
  template:
    metadata:
      labels:
        app: planner
        dns-policy: enabled        
    spec:
      restartPolicy: Always
      containers:
      - name: planner
        image: manloralm/planner:v1.23
        securityContext:
          allowPrivilegeEscalation: false        
        command: ["bash"]
        args:
        - "-c"
        - "./wait-for-it.sh weatherservice:9090 -t 500 && ./wait-for-it.sh toposervice:8181 -t 500 && ./wait-for-it.sh rabbitmq:5672 -t 500 && java -jar planner.jar"
        env:
        - name: TOPO_HOST
          value: toposervice
        - name: TOPO_PORT
          value: "8181"
        - name: GRPC_CLIENT_WEATHERSERVER_ADDRESS
          value: static://weatherservice:9090
        - name: SPRING_RABBITMQ_HOST
          value: rabbitmq
        - name: SPRING_RABBITMQ_PORT
          value: "5672"
        - name: SPRING_RABBITMQ_USERNAME
          value: root
        - name: SPRING_RABBITMQ_PASSWORD
          value: password
  replicas: 1