# TOPO
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: topo
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: Recreate
      networking/allow-mongodb-access: "true"
      networking/allow-internet-access-to-toposervice: "true"      
  template:
    metadata:
      labels:
        app: toposervice
        dns-policy: enabled
    spec:
      restartPolicy: Always
      containers:
      - name: toposervice
        image: manloralm/toposervice:v1.23
        securityContext:
          allowPrivilegeEscalation: false        
        env:
        - name: SPRING_DATA_MONGODB_HOST
          value: mongodb
        - name: SPRING_DATA_MONGODB_PORT
          value: "27017"
        - name: SPRING_DATA_MONGODB_DATABASE
          value: topoDB
        - name: SPRING_DATA_MONGODB_AUTHENTICATION-DATABASE
          value: admin
        - name: SPRING_DATA_MONGODB_USERNAME
          value: root
        - name: SPRING_DATA_MONGODB_PASSWORD
          value: password
        ports:
        - containerPort: 8181
  replicas: 1

---
apiVersion: v1
kind: Service
metadata:
  name: toposervice
  labels:
    app: toposervice
spec:
  selector:
    app: toposervice
  ports:
  - port: 8181
    targetPort: 8181
    name: topo-port
  type: ClusterIP