apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysqldb
spec:
  selector:
    matchLabels:
      app: mysqldb
  template:
    metadata:
      labels:
        app: mysqldb
    spec:
      containers:
        - name: mysql
          image: mysql:latest
          env:
          - name: MYSQL_DATABASE
            value: books
          - name: MYSQL_ROOT_PASSWORD
            value: pass

---
apiVersion: v1
kind: Service
metadata:
  name: mysqldb
spec:
  type: ClusterIP
  selector:
    app: mysqldb
  ports:
    - port: 3306