{{ if and .Values.networkPolicies.enabled .Values.networkPolicies.communication.topo-mongo }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: topo-to-mongo
spec:
  podSelector:
    matchLabels:
      app: toposervice
  egress:
    - to:
      - podSelector:
          matchLabels:
            app: mongodb
      ports:
        - port: 27017
          protocol: TCP
{{ end }}