version: '3.9'

services:
  mysql:
    image: mysql:8.0.22
    restart: on-failure
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_DATABASE=eoloplantsDB
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - 3306:3306
    volumes:
      - ./data/mysql:/var/lib/mysql

  mongo:
    image: mongo:jammy
    restart: on-failure
    environment:
      - MONGO_PORT=27017
      - MONGO_HOST=mongo
      - MONGO_INITDB_DATABASE=topo
    ports:
      - 27017:27017
    volumes:
      - ./data/mongo:/data/db

  rabbitmq:
    image: rabbitmq:3.11.10
    restart: on-failure
    environment:
      - RABBIT_PORT=5672
      - RABBIT_USER=root
      - RABBIT_PASS=password    
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq
