services:
  mysql:
    image: mysql:8.0
    hostname: mysql
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_DATABASE=eoloplantsDB
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - 3306:3306
    volumes:
      - ./data/mysql:/var/lib/mysql
    restart: on-failure

  mongo:
    image: mongo:5.0-focal
    hostname: mongodb
    environment:
      - MONGO_PORT=27017
      - MONGO_HOST=mongodb
      - MONGO_INITDB_DATABASE=topoDB
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password      
    ports:
      - 27017:27017
    volumes:
      - ./data/mongo:/data/db
    restart: on-failure

  rabbitmq:
    image: rabbitmq:3.11-management
    hostname: rabbitmq
    environment:
      - RABBITMQ_PORT=5672
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=password  
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq
    restart: on-failure
