apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: eoloplanner-ingress
spec:
  rules:
  - http:
      paths:
      - path: {{ .Values.ingress.frontPath }}
        pathType: Prefix
        backend:
          service:
            name: serverservice
            port:
              number: 8080
      - path: {{ .Values.ingress.topoPath }}/(.+)
        pathType: Prefix
        backend:
          service:
            name: toposervice
            port:
              number: 8181
    #host: {{ .Values.ingress.host }}