apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: eoloplanner-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: {{ .Values.ingress.frontPath }}
        pathType: ImplementationSpecific
        backend:
          service:
            name: serverservice
            port:
              number: 8080
      - path: {{ .Values.ingress.topoPath }}/(.+)
        pathType: ImplementationSpecific
        backend:
          service:
            name: toposervice
            port:
              number: 8181